version = 5.5.0
archive_dir = /etc/letsencrypt/archive/autobizlab.store
cert = /etc/letsencrypt/live/autobizlab.store/cert.pem
privkey = /etc/letsencrypt/live/autobizlab.store/privkey.pem
chain = /etc/letsencrypt/live/autobizlab.store/chain.pem
fullchain = /etc/letsencrypt/live/autobizlab.store/fullchain.pem
[renewalparams]
account = 38a81118117fe0b9c631f46c29f4195c
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
[acme_renewal_info]
ari_retry_after = 2026-05-13T08:20:09
